# Site settings
title: zk's blog
email: ynzkai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Zk's blog copyright 2015, Designed by zk.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zkai.me" # the base hostname & protocol for your site
twitter_username: ynzkai
github_username:  ynzkai

# Build settings
markdown: kramdown
